[build]
  publish = "/"
  command = ""

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
